connectors:
  matrix:
    # Required
    mxid: "@bot_regex_clf:bot.parsi.ai"
    password: "M@hdiF@zli17"
    rooms:
      'main': '#matrix:bot.parsi.ai'
    # Optional
    homeserver: "https://bot.parsi.ai"
    nick: "NLP_HW2_17"  # The nick will be set on startup
    enable_encryption: True

skills:
  tooti:
    path: skills/tooti_skill.py
  accept_invites:
    path: skills/accept_invite.py
  match_regex:
    path: skills/match_regex.py
  add_regex:
    path: skills/add_regex.py
  extract_regex:
    path: skills/extract_regex.py
